const replacements: Array<[RegExp, string]> = [
    [/n\?n\?o \?/g, "não é"],
    [/N\?n\?o \?/g, "Não é"],
    [/n\?n\?o/g, "não"],
    [/N\?n\?o/g, "Não"],
    [/sess\?n\?o/g, "sessão"],
    [/autocompreens\?n\?o/g, "autocompreensão"],
    [/voc\?/g, "você"],
    [/Voc\?/g, "Você"],
    [/n\?o/g, "não"],
    [/N\?o/g, "Não"],
    [/tamb\?m/g, "também"],
    [/al\?m/g, "além"],
    [/at\? /g, "até "],
    [/ at\?/g, " até"],
    [/j\?/g, "já"],
    [/est\?/g, "está"],
    [/at\?ndimento/g, "atendimento"],
    [/at\?n\?\?o/g, "atenção"],
    [/sess\?es/g, "sessões"],
    [/sess\?o/g, "sessão"],
    [/Psic\?loga/g, "Psicóloga"],
    [/psic\?loga/g, "psicóloga"],
    [/psic\?logo/g, "psicólogo"],
    [/psicol\?gica/g, "psicológica"],
    [/psicol\?gico/g, "psicológico"],
    [/cl\?nica/g, "clínica"],
    [/cl\?nico/g, "clínico"],
    [/cl\?nicos/g, "clínicos"],
    [/cl\?nicas/g, "clínicas"],
    [/cl\?nicar/g, "clinicar"],
    [/rela\?\?es/g, "relações"],
    [/rela\?\?o/g, "relação"],
    [/localiza\?\?n\?o/g, "localização"],
    [/localiza\?\?o/g, "localização"],
    [/avalia\?\?es/g, "avaliações"],
    [/avalia\?\?o/g, "avaliação"],
    [/condi\?\?es/g, "condições"],
    [/constru\?\?o/g, "construção"],
    [/interven\?\?o/g, "intervenção"],
    [/transi\?\?es/g, "transições"],
    [/transi\?\?o/g, "transição"],
    [/dire\?\?o/g, "direção"],
    [/organiza\?\?o/g, "organização"],
    [/desorganiza\?\?o/g, "desorganização"],
    [/reorganiza\?\?o/g, "reorganização"],
    [/reconstru\?\?o/g, "reconstrução"],
    [/reconex\?o/g, "reconexão"],
    [/conex\?o/g, "conexão"],
    [/compreens\?o/g, "compreensão"],
    [/diagn\?sticos/g, "diagnósticos"],
    [/diagn\?stico/g, "diagnóstico"],
    [/r\?tulo/g, "rótulo"],
    [/v\?nculos/g, "vínculos"],
    [/v\?nculo/g, "vínculo"],
    [/ambival\?ncia/g, "ambivalência"],
    [/press\?o/g, "pressão"],
    [/exaust\?o/g, "exaustão"],
    [/reflex\?es/g, "reflexões"],
    [/reflex\?o/g, "reflexão"],
    [/decis\?es/g, "decisões"],
    [/decis\?o/g, "decisão"],
    [/pr\?prias/g, "próprias"],
    [/pr\?prios/g, "próprios"],
    [/pr\?pria/g, "própria"],
    [/pr\?prio/g, "próprio"],
    [/pr\?ticas/g, "práticas"],
    [/pr\?tica/g, "prática"],
    [/pr\?tico/g, "prático"],
    [/pr\?ticos/g, "práticos"],
    [/pr\?ximas/g, "próximas"],
    [/pr\?xima/g, "próxima"],
    [/pr\?ximo/g, "próximo"],
    [/m\?dico/g, "médico"],
    [/psiqui\?trico/g, "psiquiátrico"],
    [/g\?nero/g, "gênero"],
    [/m\?nimo/g, "mínimo"],
    [/f\?cil/g, "fácil"],
    [/poss\?vel/g, "possível"],
    [/dif\?ceis/g, "difíceis"],
    [/dif\?cil/g, "difícil"],
    [/r\?pidas/g, "rápidas"],
    [/r\?pida/g, "rápida"],
    [/\?tico/g, "ético"],
    [/\?tica/g, "ética"],
    [/terap\?utica/g, "terapêutica"],
    [/terap\?utico/g, "terapêutico"],
    [/met\?fora/g, "metáfora"],
    [/aut\?ntica/g, "autêntica"],
    [/experi\?ncias/g, "experiências"],
    [/experi\?ncia/g, "experiência"],
    [/hist\?ria/g, "história"],
    [/conte\?dos/g, "conteúdos"],
    [/conte\?do/g, "conteúdo"],
    [/informa\?\?es/g, "informações"],
    [/informa\?\?o/g, "informação"],
    [/Pol\?tica/g, "Política"],
    [/pol\?tica/g, "política"],
    [/Esp\?rito/g, "Espírito"],
    [/S\?o/g, "São"],
    [/Higien\?polis/g, "Higienópolis"],
    [/Ang\?lica/g, "Angélica"],
    [/metr\?/g, "metrô"],
    [/come\?ar/g, "começar"],
    [/come\?a/g, "começa"],
    [/cansa\?o/g, "cansaço"],
    [/quest\?es/g, "questões"],
    [/sa\?de/g, "saúde"],
    [/\?nico/g, "único"],
    [/\?nica/g, "única"],
    [/p\?blico/g, "público"],
    [/apr\?ximar/g, "aproximar"],
    [/apr\?xima/g, "aproxima"],
    [/atrav\?ssando/g, "atravessando"],
    [/atrav\?ssam/g, "atravessam"],
    [/atrav\?ssada/g, "atravessada"],
    [/desej\?/g, "deseja"],
    [/Inicio/g, "Início"],
    [/Localizacao/g, "Localização"],
    [/Avaliacao/g, "Avaliação"],
    [/avaliacao/g, "avaliação"],
    [/Pagina/g, "Página"],
    [/pagina/g, "página"],
];

export function fixPt(text: string | undefined | null) {
    if (!text) return "";

    let value = text;

    for (const [pattern, replacement] of replacements) {
        value = value.replace(pattern, replacement);
    }

    return value;
}

export function stripInlineHtml(text: string | undefined | null) {
    return fixPt(text).replace(/<[^>]*>/g, "").replace(/\s+/g, " ").trim();
}
